name: Branch Deployment Pipeline
description: Run tests, create tag, publish image to Docker Hub, deploy to environment

on:
  push:
    branches:
      - "main"
      - "staging"
      - "feature/**"
      - "patch/**"
      - "ci/**"
      - "doc/**"
      - "performance/**"
      - "refactor/**"
  workflow_dispatch:

permissions:
  id-token: write # REQUIRED for OIDC
  contents: write # REQUIRED for tagging and creating GitHub releases

jobs:
  generate-tag-and-version:
    name: Validate branch and generate tag and version
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version.outputs.tag }}
      additional_tags: ${{ steps.version.outputs.additional_tags }}
      deployment_type: ${{ steps.validate-branch.outputs.deployment_type }}
      ticket: ${{ steps.validate-branch.outputs.ticket }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 50 # Fetch recent history and tags for version calculation
          fetch-tags: true

      - name: Validate branch name
        id: validate-branch
        uses: ./.github/actions/validate-branch

      - name: Calculate version
        id: version
        uses: ./.github/actions/calculate-version
        with:
          deployment_type: ${{ steps.validate-branch.outputs.deployment_type }}
          ticket: ${{ steps.validate-branch.outputs.ticket }}

  publish-tag:
    name: Publish Tag
    runs-on: ubuntu-latest
    needs: [generate-tag-and-version]
    outputs:
      tag: ${{ steps.git_tag.outputs.tag }}
      release_url: ${{ steps.github_release.outputs.release_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Git tag
        id: git_tag
        uses: ./.github/actions/create-git-tag
        with:
          tag: ${{ needs.generate-tag-and-version.outputs.tag }}

      - name: Create GitHub release
        if: needs.generate-tag-and-version.outputs.deployment_type == 'release' || needs.generate-tag-and-version.outputs.deployment_type == 'candidate'
        id: github_release
        uses: ./.github/actions/create-github-release
        with:
          tag: ${{ steps.git_tag.outputs.tag }}

  publish-image:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    needs: [generate-tag-and-version, publish-tag]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Publish Docker Image
        id: publish_image
        uses: ./.github/actions/publish-image
        with:
          tag: ${{ needs.publish-tag.outputs.tag }}
          additional_tags: ${{ needs.generate-tag-and-version.outputs.additional_tags }}
          deployment_type: ${{ needs.generate-tag-and-version.outputs.deployment_type }}
          ticket: ${{ needs.generate-tag-and-version.outputs.ticket }}
          docker_registry: ${{ vars.DOCKER_REGISTRY }}
          docker_image_name: ${{ vars.DOCKER_IMAGE_NAME }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  summary:
    name: Pipeline Summary
    runs-on: ubuntu-latest
    needs:
      [
        generate-tag-and-version,
        publish-tag,
        publish-image,
      ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Output summary
        shell: bash
        run: |
          echo "# Pipeline Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch Type:** \`${{ needs.generate-tag-and-version.outputs.deployment_type }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Tag:** \`${{ needs.generate-tag-and-version.outputs.tag }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **GitHub Release:** \`${{ needs.publish-tag.outputs.release_url }}\`" >> $GITHUB_STEP_SUMMARY
