name: "Output Build Summary"
description: "Outputs a formatted summary of the build to GitHub Step Summary"

inputs:
  branch_name:
    description: "Branch name"
    required: true
  branch_type:
    description: "Type of branch (release or development)"
    required: true
  docker_tag:
    description: "Docker tag used"
    required: true
  registry:
    description: "Docker registry/organization"
    required: true
  image:
    description: "Docker image"
    required: true
  metadata:
    description: "Docker image metadata"
    required: true
  release_url:
    description: "GitHub release URL (for release branches)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Generate summary
      shell: bash
      run: |
        echo "## Job Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Branch:** ${{ inputs.branch_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Branch Type:** ${{ inputs.branch_type }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Docker Image:** ${{ inputs.image }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Metadata:** ${{ inputs.metadata }}" >> $GITHUB_STEP_SUMMARY

        if [ -n "${{ inputs.additional_tags }}" ]; then
          echo "- **Additional Tags:** ${{ inputs.additional_tags }}" >> $GITHUB_STEP_SUMMARY
        fi

        if [ -n "${{ inputs.release_url }}" ]; then
          echo "- **GitHub Release:** ${{ inputs.release_url }}" >> $GITHUB_STEP_SUMMARY
        fi

        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Image pushed successfully! :rocket:" >> $GITHUB_STEP_SUMMARY

        echo "image=${{ inputs.image }}" >> $GITHUB_OUTPUT
        echo "metadata=${{ inputs.metadata }}" >> $GITHUB_OUTPUT
